import type { TemplateConfig } from '../types';
import { TemplateRenderer, getCanvasDimensions, generateSVG } from './renderer';

export async function exportToPNG(
  config: TemplateConfig,
  _filename?: string
): Promise<Blob> {
  const dims = getCanvasDimensions(config.orientation);
  const canvas = document.createElement('canvas');
  canvas.width = dims.width;
  canvas.height = dims.height;

  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Failed to get canvas context');

  const renderer = new TemplateRenderer(ctx, dims.width, dims.height);
  renderer.render(config);

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error('Failed to create PNG blob'));
    }, 'image/png');
  });
}

export function exportToSVG(config: TemplateConfig): string {
  return generateSVG(config);
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadText(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  downloadBlob(blob, filename);
}

// Generate templates.json entry
export function generateTemplateEntry(
  name: string,
  filename: string,
  categories: string[],
  isLandscape: boolean
): object {
  return {
    name,
    filename,
    iconCode: '\ue9fe', // Default custom icon
    categories,
    ...(isLandscape && { landscape: true }),
  };
}

// Generate SSH install script
export function generateInstallScript(
  filename: string,
  name: string,
  categories: string[]
): string {
  const entry = JSON.stringify({
    name,
    filename,
    iconCode: '\ue9fe',
    categories,
  }, null, 2);

  return `#!/bin/bash
# reMarkable Template Install Script
# Generated by remarkable-templates

DEVICE_HOST="\${1:-10.11.99.1}"
TEMPLATE_DIR="/usr/share/remarkable/templates"

echo "Installing template: ${filename}"

# Copy PNG file
scp ${filename}.png root@$DEVICE_HOST:$TEMPLATE_DIR/

# Copy SVG file if exists
if [ -f "${filename}.svg" ]; then
  scp ${filename}.svg root@$DEVICE_HOST:$TEMPLATE_DIR/
fi

# Add to templates.json
ssh root@$DEVICE_HOST "cd $TEMPLATE_DIR && \\
  cp templates.json templates.json.bak && \\
  jq '.templates += [${entry.replace(/"/g, '\\"')}]' templates.json > templates.json.tmp && \\
  mv templates.json.tmp templates.json"

# Restart xochitl
echo "Restarting xochitl..."
ssh root@$DEVICE_HOST "systemctl restart xochitl"

echo "Template installed successfully!"
`;
}

// Export both PNG and SVG as a zip (using JSZip if available, otherwise separate downloads)
export async function exportBundle(
  config: TemplateConfig,
  filename: string,
  options: { includePNG: boolean; includeSVG: boolean; includeScript: boolean }
) {
  const results: { name: string; blob: Blob }[] = [];

  if (options.includePNG) {
    const png = await exportToPNG(config, filename);
    results.push({ name: `${filename}.png`, blob: png });
    downloadBlob(png, `${filename}.png`);
  }

  if (options.includeSVG) {
    const svg = exportToSVG(config);
    downloadText(svg, `${filename}.svg`, 'image/svg+xml');
  }

  if (options.includeScript) {
    const script = generateInstallScript(filename, filename, ['Creative']);
    downloadText(script, `install_${filename}.sh`, 'text/x-shellscript');
  }

  return results;
}
